version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - 201803.Resume.Naoki.Mihara.pdf
    - styles/main.css
    - images/*

